import { Injectable } from "@angular/core";


@Injectable()
export class NationalityService {
    getNationality(){
        return this.nationalities;
    }

        public nationalities:Array<string> = [
        'Afghan',
        'Albanian',
        'Algerian',
        'American',
        'Andorran',
        'Angolan',
        'Argentine',
        'Armenian',
        'Aromanian',
        'Aruban',
        'Australian',
        'Austrian',
        'Azerbaijani',
        'Bahamian',
        'Bahraini',
        'Bangladeshi',
        'Barbadian',
        'Basotho',
        'Belarusian',
        'Belgian',
        'Belizean',
        'Bermudian',
        'Boer',
        'Bosniak',
        'Brazilian',
        'Breton',
        'British',
        'Indians',
        'Pakistani',
        'Chinese',
        'Dutch',
        'East Timorese',
        'Ecuadorian',
        'Egyptian',
        'Emirati',
        'English',
        'Eritrean',
        'Estonian',
        'Ethiopian',
        'Falkland Islander',
        'Finn',
        'Finnish Swedish',
        'Fijian',
        'Filipino',
        'French citizen',
        'Georgian',
        'German',
        'Baltic German',
        'Ghanaian',
        'Gibraltar',
        'Greeks',
        'Greek Macedonian',
        'Grenadian',
        'Guatemalan',
        'Guianese (French)',
        'Guinean',
        'Guinea-Bissau nationals',
        'Guyanes',
        'Haitian',
        'Honduran',
        'Hong Kong',
        'Hungarian',
        'Icelanders',
        'I-Kiribati',
        'Indian',
        'Indonesian',
        'Iranian',
        'Iraqi',
        'Irish',
        'Israelis',
        'Italians',
        'Ivoirians',
        'Jamaicans',
        'Japanese',
        'Jordanians',
        'Kazakhs',
        'Kenyans',
        'Koreans',
        'Kosovars',
        'Kurds',
        'Kuwaitis',
        'Kyrgyzs',
        'Lao',
        'Latvians',
        'Lebanese',
        'Liberians',
        'Libyans',
        'Liechtensteiners',
        'Lithuanians',
        'Luxembourgers',
        'Macedonians',
        'Malagasy',
        'Malaysians',
        'Malawians',
        'Maldivians',
        'Malians',
        'Maltese',
        'Manx',
        'Mauritians',
        'Mexicans',
        'Moldovans',
        'Moroccans',
        'Mongolians',
        'Montenegrins',
        'Namibians',
        'Nepalese',
        'New Zealanders',
        'Nicaraguans',
        'Nigeriens',
        'Nigerians',
        'Norwegians',
        'Pakistanis',
        'Palauans',
        'Palestinians',
        'Panamanians',
        'Papua New Guineans',
        'Paraguayans',
        'Peruvians',
        'Poles',
        'Portuguese',
        'Puerto Ricans',
        'Quebecers',
        'Romanians',
        'Russians',
        'Baltic Russians',
        'Rwandans',
        'Salvadorans',
        'São Tomé and Príncipe',
        'Saudis',
        'Scots',
        'Senegalese',
        'Serbs',
        'Sierra Leoneans',
        'Singaporeans',
        'Sindhian',
        'Slovaks',
        'Slovenes',
        'Somalis',
        'Somalilanders',
        'South Africans',
        'Spaniards',
        'Sri Lankans',
        'St Lucians',
        'Sudanese',
        'Surinamese',
        'Swedes',
        'Swiss',
        'Syriacs',
        'Syrians',
        'Tajik',
        'Tanzanians',
        'Thais',
        'Tibetans',
        'Trinidadians',
        'Tuvaluans',
        'Ugandans',
        'Ukrainians',
        'Uruguayans',
        'Vanuatuans',
        'Venezuelans',
        'Vietnamese',
        'Welsh',
        'Yemenis',
        'Zambians',
        'Zimbabweans'
    ]
}