// lang-bn.ts

export const LANG_BN_NAME: string = 'bn';

export const LANG_BN_TRANS = {
    'Attributes': 'বৈশিষ্ট্যাবলী',
    'Category': 'বিভাগ',
    'Author': 'লেখক',
    'Publisher': 'প্রকাশক',
    'Testimonials': 'প্রশংসাপত্র',
    'Popular List': 'জনপ্রিয় তালিকা',
    'Pre Order': 'পূর্বাদেশ',
    'Review': 'পর্যালোচনা',
    'Cart': 'কার্ট',
    'Bundle Items': 'এই বান্ডেল এর বই সমূহ',
    'Related Bundles': 'এই বই এর বান্ডেল সমূহ',
    'You Are Saving': 'আপনি সাশ্রয় করছেন',
    'Bundle Savings': 'বান্ডেল ছাড়',
    'Bundle Price': 'বান্ডেল মূল্য',
    'Bundle': 'বান্ডেল',

    'Customer': 'গ্রাহক',
    'Care': 'সেবা',
    'Search': 'খুঁজুন',

    'cash_on_delivery': 'ক্যাশ অন ডেলিভারি',
    'service_availability': 'সেবার আওতা',
    'payment_option': 'পেমেন্ট অপশন্‌স',
    'CREATE ACCOUNT': 'নতুন অ্যাকাউন্ট',
    'Create Account': 'নতুন অ্যাকাউন্ট',
    'Name': 'নাম',
    'Email/Phone': 'এমাইল/ফোন',
    'Confirm Password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'Already have an account?': 'অ্যাকাউন্ট ইতিপূর্বে খোলা হয়েছে?',
    'Sign in': 'সাইন ইন করুন',
    'Password should be minimum 6 characters': 'পাসওয়ার্ড সর্বনিন্ম ৬ অক্ষর/সংখ্যা হতে হবে',
    'Sign In': 'সাইন ইন',
    'Sign in/up': 'সাইন ইন/আপ',
    'Order Tracker': 'অর্ডার ট্র্যাক করুন',
    'Phone, Email or Username': 'ফোন, ইমেইল, ইউজার-নেম',
    'Password': 'পাসওয়ার্ড',
    'New Account': 'নতুন অ্যাকাউন্ট',
    'Dont have an account?': 'কোন অ্যাকাউন্ট নেই?',
    'Forgot your password?': 'পাসওয়ার্ড ভুলে গেছেন?',
    'Name should be minimum 4 characters':'নাম সর্বনিন্ম ৪ সংখ্যা/অক্ষর হতে হবে',
    'Name is required':'নাম বাধ্যতামূলক',
    'Passwords dont match.':'পাসওয়ার্ড মিলছে না',
    'Email/Phone is invalid.': 'এমাইল/ফোন সঠিক নয়',

    'Log Out': 'লগ আউট',

    'add_to_cart': 'কার্ট যোগ',
    'free_delivery': 'সরবরাহ খরচ মুক্ত',
    'added_to_cart': 'কার্ট যোগকৃত',
    'buy_now': 'কার্টে যান',
    'similar_books': 'অনুরূপ বইসমূহ',
    'write_review': 'রিভিউ লিখুন',
    'View Details': 'বিস্তারিত দেখুন',
    'View More Books...': 'আরও বই দেখুন ...',

    'price': 'মূল্য',
    'bundle_price': 'বান্ডেল মূল্য',
    'boibazar_price': 'বইবাজার মূল্য',
    'boibazar_offer_price': 'বইবাজার অফার মূল্য',
    'Off': 'ছাড়',
    'OFF': 'ছাড়',
    'Look Inside': 'ভেতরে পড়ুন',



    'previous_price': 'মূল্য',
    'shipping_charge': 'বহন খরচ',
    'quantity': 'মোট সংখ্যা',
    'Book Name': 'বইয়ের নাম',
    'rating': 'রেটিং',


    'home_heading': 'হোম',
    'books_heading': 'বইসমূহ',
    'shop_heading': 'শপিং',
    'know_us_heading': 'আমাদেরকে জানুন',
    'support_heading': 'সহায়িকা',
    'policy_heading': 'নীতিমালা',

    'Categories': 'ক্যাটাগরিস',
    'All': 'সকল',
    'Authors': 'লেখক',
    'Publishers': 'প্রকাশক',
    'view_all': 'সব দেখুন',

    'Home': 'হোম',
    'All Books': 'সকল বই',
    'Boimela 2018': 'বইমেলা ২০১৮',
    'Islamic Books': 'ইসলামিক বই',

    'Profile Details': 'প্রোফাইল',
    'Support': 'সহায়তা',
    'About Us': 'আমাদের সম্পর্কে',
    'Contact Us': 'যোগাযোগ করুন',
    'Purchase': 'ক্রয়কৃত',

    'News': 'খবর',
    'Stay Connected': 'যুক্ত থাকুন',
    'Subscribe': 'সাবস্ক্রাইব',

    'faq': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
    'details': 'পরিচিতি',
    'How To Order': 'কিভাবে অর্ডার করবেন',

    'Terms of Use': 'ব্যবহারের শর্তাবলী',

    'Buying Policy': 'ক্রয় নীতি',
    'Privacy Policy': 'গোপনীয়তা নীতি',


    'new_releases': 'নতুন উন্মোচিত',
    'foreign_books': 'বিদেশী বই',
    'best_seller': 'সর্বাধিক বিক্রিত',
    'most_popular': 'সবচেয়ে জনপ্রিয়',

    'Overall Ratings': 'সার্বিক রেটিং',
    'Help_Support': 'সহযোগিতা',
    'Help_Desk': 'হেল্প ডেস্ক',

    'get_In_Touch': 'আমাদের সাথে যোগাযোগ করুন',
    'contact_Info': 'যোগাযোগের তথ্য',
    'social_Networking': 'সামাজিক যোগাযোগ',
    'boibazar': 'বইবাজার ',

    'mobile': 'মোবাইল: ',
    'contact_no': ' ০১৭ ২৬২৬ ২০২০',

    'email': 'ইমেইল: ',
    'email_address': 'info@boibazar.com',

    'Not More Than 10': '১০ টির বেশি নয়',

    'items': 'আইটেম্‌স',
    'Total': 'সর্বমোট',
    'Promo Code': 'প্রোমো কোড',
    'Apply': 'প্রয়োগ করুন',
    'Order Summary': 'অর্ডার সামারি',
    'Continue Shopping': 'আরো কেনাকাটা করুন',
    'Your Shopping Cart': 'আপনার কার্ট',
    'Delivery Charge': 'ডেলিভারি চার্জ',
    'Sub-total': 'মোট',
    'Checkout': 'চেকআউট',
    'Have your say': 'আপনি যা বলতে চান',
    'Discount': 'ডিসকাউন্ট',
    'Coupon Code': 'কুপন কোড',
    'Books': 'বইসমূহ',
    'Quantity': 'মোট সংখ্যা',
    'Price': 'মূল্য',
    'Action': 'অ্যাকশন',
    'Remove': 'অপসারণ করুন',
    'Start Here': 'এখানে শুরু করুন',
    'You dont have any item in your cart': 'আপনার কার্টে কোন বই নেই',
    'You have not purchased any book': 'আপনি কোন বই কিনেন-নি',

    'Mobile': 'মোবাইল',

    'Payment Method': 'মূল্য পরিশোধ পদ্ধতি',
    'Gift Wrap': 'গিফট রাপ',
    'Taka': 'টাকা',
    'Tk.': '৳',

    'Shipping Address': 'যে ঠিকানায় পাঠাবো',
    'Contact Name': 'আপনার নাম',
    'should be minimum 4 characters': 'সর্বনিন্ম ৪ অক্ষর হতে হবে',

    'Your primary address is following': 'আপনার প্রাথমিক ঠিকানা',
    "wrong": "ভুল",
    'District': 'শহর / জেলা',
    'Thana': 'থানা',
    'Address': 'ঠিকানা',
    'Number': 'নম্বর',
    'Alternate': 'বিকল্প',
    'Use it as primary': 'প্রাথমিকভাবে ব্যবহার করুন',
    'Save': 'সেভ',
    '&': 'এবং',
    'Continue': 'আরম্ভ করুন',
    'Back': 'পিছনে',
    'Use New Address': 'নতুন ঠিকানা ব্যবহার করুন',
    'Use This Address': 'এই ঠিকানা ব্যাবহার করুন',
    'Wrapping Charge': 'মোড়কের চার্জ',
    'Payable Total Amount': 'প্রদানযোগ্য মোট পরিমান',
    'SIMILAR BOOKS YOU MIGHT LIKE': 'আপনার পছন্দের অনুরূপ বইসমূহ',

    'How to Pay': 'যেভাবে টাকা প্রদান করবেন',
    'Click on "Confirm Order".': '"অর্ডার নিশ্চিত করুন" এ ক্লিক করুন।',
    'Your order will be placed immediately.': 'আপনার অর্ডারটি সাথে সাথে কার্যকর হবে।',
    'You will get the parcel of happiness within 3-5 working days(in Dhaka).': 'পার্সেলটি ৩-৫ কর্মদিবসের মধ্যে আপনার নির্দিষ্ট ঠিকানায় পৌছে যাবে (ঢাকার মধ্যে)।',
    'After receiving the parcel, pay to the delivery man': 'পার্সেলটি গ্রহণ ও বুঝে পাওয়ার পর, ডেলিভারি কর্তাকে অর্ডারের টাকা পরিশোধ করুন।',
    'Return Policy Notice': '* আপনার যদি পার্সেল সংক্রান্ত কোনো সমস্যা থাকে, তাহলে আপনি খুব সহজে অর্ডারটি ফেরত দিতে পারবেন আমাদের "হ্যাপি রিটার্ন পলিসি" এর মাধ্যমে।',
    'Cash On Delivery': 'ক্যাশ অন ডেলিভারি',
    'Pay with cash after receiving your order': 'আপনার অর্ডারটি/পার্সেল গ্রহণের পর  টাকা প্রদান করুন',
    'Your Payable amount': 'আপনার প্রদানযোগ্য টাকার পরিমান',
    'I agree to start': 'আমি সকল',
    'I agree to end': 'সাথে সম্মতি হচ্ছি',
    'Privacy Policies': 'গোপনীয়তা নীতির',
    'Terms of Uses': 'শর্ত',
    'Confirm Order': 'অর্ডার নিশ্চিত করুন',
    '9am_7pm': 'সকাল ৯ টা - সন্ধ্যা ৭ টা',
    'address': 'লেভেল: ১৪, সাত্তারা সেন্টার ৩০/এ ভিআইপি রোড, নয়া পল্টন, ঢাকা',
    'copyright': 'কপিরাইট © 2017 BoiBazar.com লিমিটেড । সর্বস্বত্ব সংরক্ষিত ।',

    'pay_cash_at_your_doorstep': 'আপনার দোরগোড়ায় নগদ অর্থ প্রদান',
    'all_over_bangladesh': 'সমগ্র বাংলাদেশ',

    'return_policy': 'প্রত্যাবর্তন নীতিমালা: ',
    'return_policy_msg': 'ফেরত গ্রহণযোগ্য যদি কাঙ্খিত পণ্য না দেয়া হয়, তখন ক্রেতাকে কোনো ফি দিতে হবে না অন্যথায় পণ্য রাখতে  হবে অথবা বহন খরচ দিয়ে বই ফেরত দেয়া যাবে ।',
    'seller_guarantees': 'বিক্রেতা নিশ্চয়তা: ',
    'seller_guarantees_mgs': 'নির্ধারিত সময়ের মধ্যে বই পোঁছে দেয়ার নিশ্চয়তা ।',

    'Politics': 'রাজনীতি',
    'Computer_Accessories': 'কম্পিউটার এক্সেসরিস',
    'Novel': 'উপন্যাস',
    'New_Released': 'নতুন উন্মোচিত',
    'Math_Sci_Tech': 'গণিত, বিজ্ঞান ও প্রযুক্তি',
    'slogan': 'বাংলাদেশের সর্ববৃহৎ বই ভাণ্ডার',
    'password_reset': "পাসওয়ার্ড পুনরুদ্ধার",
    "password_length_error": 'পাসওয়ার্ড সর্বনিম্ন ৪ ডিজিট হতে হবে।',
    "password_match": "পাসওয়ার্ড মিলেনি।",
    "enter_email_phone": "ইমেইল অথবা ফোন নাম্বার দিন",
    "invalid_email_phone": "ভুল তথ্য",
    "submit": "দাখিল করুন",
    "condition_applicable": "শর্ত প্রযোয্য",
    "Translator": "অনুবাদক",
    "Return Policy": "প্রত্যাবর্তন নীতি",
    'Articles': 'প্রবন্ধ',
    'Blog': 'ব্লগ',


    'Title': 'শিরোনাম',
    'Description': 'বর্ণনা',
    'Book/Bundle': 'বই/বান্ডেল',
    'Book': 'বই',
    'Search By Any': 'যে কোনো কিছু লিখুন (অর্থাৎ: বই, প্রকাশক, লেখক, ক্যাটাগরি, তারিখ,...)',

    'Calculation Summary': 'হিসাব সংক্ষেপ',
    'Book Summary': 'বই সংক্ষেপ',

    'Book Total': 'মোট',
    'Total Book': 'মোটবই',

    'Grand Total': 'সর্বমোট',
    'Order No': 'অর্ডার নম্বর',
    'Pay Now': 'এখনি পরিশধ করুন',

    'Submit': 'সাবমিট',

    'Please Enter "Phone No" or "Order No" to see your Order Status': 'আপনার অর্ডার স্ট্যাটাস দেখতে "মোবাইল নম্বর" অথবা "অর্ডার নম্বর" লিখুন',
    'S/L': 'ক্রমিক',


    'Cancelled': 'বাতিলকৃত',
    'Confirmed': 'নিশ্চিত',
    "Payment Status": "প্যামেন্ট",
    'N/A': 'নেই',
    'Hide Details': 'বিস্তারিত আড়াল করুন',
    'Show Details': 'বিস্তারিত দেখুন',
    "Paid": "পরিশোধিত",
    "Not Paid": "পরিশোধ হয়নি",

    'Order Status': 'অর্ডার ',
    'Mobile No': 'মোবাইল নম্বর',
    'Total Price': 'সর্বমোট মূল্য',
    'Pending': 'অমীমাংসিত',
    'Orders': 'অর্ডার',
    'Order List': 'অর্ডার তালিকা',
    'Ordered At': 'অর্ডারের তারিখ',

    'Promo Code exceeded the maximum target': 'প্রোমো কোড সর্বোচ্চ টার্গেট অতিক্রম করেছে',
    'Promo Code is expired': 'প্রোমো কোডের মেয়াদ শেষ হয়ে গেছে',
    'Promo Code is Invalid': 'প্রোমো কোডটি অকার্যকর',
    'Promo Code is already used 3 times': 'প্রোমো কোডটি তিন বার ব্যবহার করা হয়েছে',
    'Your Discount percentage is': 'আপনার ডিসকাউন্টের পরিমান:',
    'out_of_print':'প্রিন্ট নেই',
    'out_of_stock': 'ষ্টকে নেই',
    'query_title':'আমরা আপনাকে সাহায্য করতে পারি।',
    'query_description':'বইবাজারে যদি আপনার প্রত্যাশিত বইটি খুঁজে না পান, একটি অনুসন্ধান দাখিলের মাধ্যমে আমাদের জানাতে পারেন।',
    'book_required':'বইয়ের নাম অবশ্যক',
    'Book Author':'বইয়ের লেখক',
    'Message':'বার্তা',
    'Submit Your Query':'অনুসন্ধান দাখিল করুন',
    'Did you not find your book':'আপনার বইটি কি খুঁজে পাননি?'
};